### ISSUE TITLE
hex package

### ISSUE THREAD

**Issue by Licenser** [Bluehouse-Technology/otter#2]
Hi friends,
first of all, this looks awesome :D, thanks for this! Now the but, any chance to get a hex package? I'm happy to help setting it up and make a PR of the needed bits, bit it's usually straight forward enough to just do `rebar3 hex publish`.

Cheers!

**Comment by Licenser** [comment]
Reading a bit more of the source a few thoughts about that.

for a useful hex package it might be required to split the server / client part.

Chances are a decent number systems that use the client will also include cowboy which can lead to potential problems (especially when using hex packages.

Also for a hex package rebar.config dependenices should probably use version ranges so they don't lock down the version to 1 exact version (this can be a major headache when hex packages depend on other hex packages)

**Comment by tsloughter** [comment]
+1 to publishing and splitting the server and client :)

**Comment by tsloughter** [comment]
Or just removing the dep on cowboy and say in the readme if you want to run the server you have to add cowboy to your deps alongside otter?

**Comment by surik** [comment]
Also, I think it is possible to have `ibrowse` as an optional dependency. Otter can work with `httpc` now and in the future it is easy to add `hackney` for example.

**Comment by cmullaparthi** [comment]
> Or just removing the dep on cowboy and say in the readme if you want to run the server you have to add cowboy to your deps alongside otter?

@tsloughter I need cowboy for the tests to run. Is there a way with rebar3 to specify that a certain dependency is only to be used when running tests?

@surik same goes for specifying ibrowse as an optional dependency. How do I express this using rebar config?

**Comment by tsloughter** [comment]
Yes, test dependencies should always be added to the test profile which is automatically used by the `eunit` and `ct` tasks:

```
{profiles, [{test, [{deps, [cowboy]}]}]}.
```

**Comment by cmullaparthi** [comment]
Thanks, looks like I'm not the only one suffering from insomnia :-)

**Comment by cmullaparthi** [comment]
Fixed in 1be0b63

**Comment by tsloughter** [comment]
Only 7:30 here :)

**Comment by cmullaparthi** [comment]
Ah, I assumed you were somewhere in Europe, my bad!

**Comment by surik** [comment]
> @surik same goes for specifying ibrowse as an optional dependency. How do I express this using rebar config?

For HTTP clients I think better just don't add any to `rebar.config` and set `http_client` to `httpc` by default. Then add some info section to `README.md` how to switch it to `ibrowse` to `hackney`. In this case, we should have some wrapper over them like there https://github.com/Bluehouse-Technology/otter/blob/master/src/otter_conn_zipkin.erl#L96
