### ISSUE TITLE
Add information about new jaeger zipkin compatible endpoint

### ISSUE THREAD

**Issue by 0xAX** [Bluehouse-Technology/otter#20]
README.md tells about:

```
...
%% example url for sending spans to Jaeger
{zipkin_collector_uri, "http://127.0.0.1:14268/api/traces?format=zipkin.thrift"},
...
```

in a case of sending of zipkin.thift messages to jaeger. But such endpoint removed since https://github.com/jaegertracing/jaeger/commit/31d43fab1270c93bfe230343c6b207be5f19abd8 and `/api/v1/spans` must is used now. 

Would be good to mention this in documentation.

**Comment by cmullaparthi** [comment]
Thanks, fixed.
