### ISSUE TITLE
Filter compiler

### ISSUE THREAD

**Issue by Licenser** [Bluehouse-Technology/otter#5]
How do you lot feel about a more readable filter language then terms encoding logic?

I use something similar for tachyon (a distributed kstat aggregator) to filter very high volumes of events with very little overhead.

The basic approach is a minimal erlangish language to express the rules, that then compiles to an erlang module to do the filtering.

This has some advantages:

1) it's a lot faster then encoded rules as it's compiled erlang code
2) it's more readable then encoded rules
3) it's very easy to change (just re-compile the ruleset)
4) you get syntax highlighting, code formating etc for 'free'

An example of rules would be here:

https://github.com/project-fifo/tachyon-aggregator/blob/master/rel/files/tachyon.rules.example

**Comment by Licenser** [comment]
I forgot I should probably have linked to the docs too: https://docs.project-fifo.net/docs/tachyon#section-rules ;)

**Comment by cmullaparthi** [comment]
Sorry about the delay in responding, I've just seen these issues. I assumed I would get notification emails when these issues are raised but that didn't happen.

I like the idea and I've seen your take on it in the otters repo. My reservation with this proposal is that to take advantage of this I would either have to bundle in a compiler into my production systems or I would have to put a patch on a live system to change the filter criteria. Both are suboptimal in my view as Tracing on live systems should only involve commands which at worst change configuration.

What are your thoughts on this?

**Comment by Licenser** [comment]
otter is bundeling whole cowboy on and shipping that to production systems without any benefit from it. 4 additional modules for an order of magnitude improvement in filtering performance seem to be a no brainer. The compiler itself is part of the ERTS and shipped anyway.

The main concern with instrumentation should be to keep the impact on the production codepath as low as possible everything else is secondary.

**Comment by cmullaparthi** [comment]
> otter is bundeling whole cowboy on and shipping that to production systems without any benefit from it. 4 additional modules for an order of magnitude improvement in filtering performance seem to be a no brainer. The compiler itself is part of the ERTS and shipped anyway.

Yes, I don't like that either. I'm trying to fix that by tweaking rebar.config but haven't had much luck so far. Perhaps I just have to modify the tests to use inets http instead.

> The main concern with instrumentation should be to keep the impact on the production codepath as low as possible everything else is secondary.

I agree with this sentiment, but my habit with years of hardening and deploying telco systems is to avoid putting a compiler in the live system.

**Comment by Licenser** [comment]
I think you're confusing code that lives in the codepath of the production system with code that lives outside of it.

**Comment by fholzhauser** [comment]
This is typically an area where preferences will always differ. I think the best would be to have a filter plugin API. I'll propose and enhancement in a separate issue, so we can discuss it there.

**Comment by fholzhauser** [comment]
0.3.0 supports filter callback configuration. i.e. you can roll your own (eventually compiled) filter.
