### ISSUE TITLE
export_all vs export

### ISSUE THREAD

**Issue by Licenser** [Bluehouse-Technology/otter#6]
Would there be objections to a PR that makes exports explicit?

Partially this comes down to taste I guess, but in my experience having explict exports makes understanding code a lot easier (i.e. you can just read over the exports to see the external API), as well as it makes dead code more obvious (unused functions that are neither exported nor used locally).

**Comment by tsloughter** [comment]
In OTP 20 `export_all` becomes a warning, so best to remove them.

**Comment by cmullaparthi** [comment]
Yep, fixed in the 0.2.0 release.
