### ISSUE TITLE
graceful handling of p-functions w/o start

### ISSUE THREAD

**Issue by Licenser** [Bluehouse-Technology/otter#7]
When the p-functions are called w/o the process having been initialized they can crash. it would be nicer if they'd simply be no-ops that way tracing could be completely 'disabled' by just not calling 'start' to begin with :)

**Comment by cmullaparthi** [comment]
I like the trick but it messes up the type specs. A better way would be to provide support for a no-op tracer, I'll look into that.

**Comment by Licenser** [comment]
it doesn't mess them up it changes them. The whole switchable provider thing will add performance overhead, allowing for undefined spans does not.
